// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/before-you-sign/PrivacyPreview.tsx": () => import("../components/mockups/before-you-sign/PrivacyPreview.tsx")
};
